### Write your name here
### This HW is due on  11/3 at 11:59 pm


This dataset is about participants who completed the personal information form and a divorce predictors scale.
The data is a modified version of the publicly available at https://archive.ics.uci.edu/ml/datasets/Divorce+Predictors+data+set (by injecting noise so you will not replicate the results on uci web- site). There are 170 participants and 54 attributes (or predictor variables) that are all real-valued. The dataset is named as divorce.csv. The last column of the CSV file is labeled y (1 means “divorce”, 0 means “no divorce”). Each column is for one feature (predictor variable), and each row is a sample (participant). A detailed explanation for each feature (predictor variable) can be found at the website link above. 

We will be using sklearn very often from now on. Please read all about it here https://scikit-learn.org/stable/index.html

## Problem 1
Please load the divorce data that is in csv form. Make sure to add Header = None when uploading it. Separate the last column as y and all other columns as x. Use all the data x and y to trian a logistic regression model using LogisticRegression function from sklearn library here
https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
Once you fit the model, make predictions on the whole data set x, report the accuracy score and the confusion matrix (Will discuss these details in lecutre on Wednesday). ( 20 points)

In [9]:
import numpy as np
import numpy.matlib
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import preprocessing
import seaborn as sns
import scipy.stats as st
import matplotlib.colors as colors
df = pd.read_csv('divorce.csv', header = None)
df.head()

0         1         2         3         4         5         6   \
0  1.560903  3.681587  3.450467  3.211998 -1.203045  0.597706 -0.970093   
1  4.153272  5.173858  4.100690  2.580173  3.305788 -1.505512 -0.029398   
2  2.226241  1.575322  2.389117  2.725405 -0.304562  2.832803  1.787779   
3  3.553458  2.859042  2.928414  1.833241  1.271119  4.165213  2.078597   
4  0.506547  1.419223  1.716153  1.319274  2.853840  0.047412 -0.016515   

         7         8         9   ...        45        46        47        48  \
0 -0.750970 -0.511495 -0.133660  ...  2.077401  1.184182  3.955069  2.608046   
1  5.702657  2.230281  4.975496  ...  3.467076  2.451984  3.504294  5.324240   
2  0.565755  1.328212  2.335353  ...  1.200917  1.241794  2.207492  1.228034   
3  4.506175  2.521628  2.747315  ...  3.196291  2.204824  3.664982  3.689508   
4  0.620795  1.202992  0.078347  ...  1.806657  2.085539  2.012551  1.899477   

         49        50        51        52        53   54  
0  2.303629  1.721660  3.275018  1.761019  1.215237  1.0  
1  4.480607  5.375248  2.270379  2.167944  2.191214  1.0  
2  0.870052  1.685040  2.341985 -0.444320  2.527452  1.0  
3  2.577677  3.171884  2.164660  1.813024  1.376033  1.0  
4  1.510134  1.373350  2.551119  0.846321 -0.066858  1.0  

[5 rows x 55 columns]

In [23]:
y = df[54]
x = df[df.columns[0:54]]

0         1         2         3         4         5         6   \
0  1.560903  3.681587  3.450467  3.211998 -1.203045  0.597706 -0.970093   
1  4.153272  5.173858  4.100690  2.580173  3.305788 -1.505512 -0.029398   
2  2.226241  1.575322  2.389117  2.725405 -0.304562  2.832803  1.787779   
3  3.553458  2.859042  2.928414  1.833241  1.271119  4.165213  2.078597   
4  0.506547  1.419223  1.716153  1.319274  2.853840  0.047412 -0.016515   

         7         8         9   ...        44        45        46        47  \
0 -0.750970 -0.511495 -0.133660  ...  3.357714  2.077401  1.184182  3.955069   
1  5.702657  2.230281  4.975496  ...  3.840590  3.467076  2.451984  3.504294   
2  0.565755  1.328212  2.335353  ...  2.941032  1.200917  1.241794  2.207492   
3  4.506175  2.521628  2.747315  ...  2.594346  3.196291  2.204824  3.664982   
4  0.620795  1.202992  0.078347  ...  1.889684  1.806657  2.085539  2.012551   

         48        49        50        51        52        53  
0  2.608046  2.303629  1.721660  3.275018  1.761019  1.215237  
1  5.324240  4.480607  5.375248  2.270379  2.167944  2.191214  
2  1.228034  0.870052  1.685040  2.341985 -0.444320  2.527452  
3  3.689508  2.577677  3.171884  2.164660  1.813024  1.376033  
4  1.899477  1.510134  1.373350  2.551119  0.846321 -0.066858  

[5 rows x 54 columns]

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import confusion_matrix
lrmodel = LogisticRegression(solver='lbfgs')
lrmodel.fit(x, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
ypredlr = lrmodel.predict(x)
print("Accuracy:",metrics.accuracy_score(y, ypredlr))
print(confusion_matrix(y, ypredlr))

Accuracy: 1.0
[[86  0]
 [ 0 84]]


### Problem 2
Now repeat problem 1 by splitting the data by 80, 20 rule. Please report your accuracy rate and confusion matrix for both the test and the train set. (20 points)

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [27]:
lrmodel = LogisticRegression(solver='lbfgs')
lrmodel.fit(x_train, y_train)

test_ypredIr = lrmodel.predict(x_test)
train_predIr = lrmodel.predict(x_train)

In [31]:
print("Accuracy test:",metrics.accuracy_score(y_test, test_ypredIr))
print(confusion_matrix(y_test, test_ypredIr))
print("\n")
print("Accuracy train:",metrics.accuracy_score(y_train, train_predIr))
print(confusion_matrix(y_train, train_predIr))

Accuracy test: 0.9411764705882353
[[11  0]
 [ 2 21]]


Accuracy train: 1.0
[[75  0]
 [ 0 61]]


### Problem 3
Out of 54 features, choose only 40 that are most improtant. Retrain the logistic model by splitting it to 70, 30. You decide how you want to pick 40 important features. Looking at statmodels summary is one way. Sklearn has a feature slection function too, check it out. https://scikit-learn.org/stable/modules/feature_selection.html. Report the accuracy and the confusion matrix. (20 points)

In [57]:
y1 = y
x1 = df[df.columns[0:40]]
x_train, x_test, y_train, y_test = train_test_split(x1, y1, test_size=0.3)

lrmodel = LogisticRegression(solver='lbfgs')
lrmodel.fit(x_train, y_train)

test_ypredIr = lrmodel.predict(x_test)
train_predIr = lrmodel.predict(x_train)

print("Accuracy test:",metrics.accuracy_score(y_test, test_ypredIr))
print(confusion_matrix(y_test, test_ypredIr))
print("\n")
print("Accuracy train:",metrics.accuracy_score(y_train, train_predIr))
print(confusion_matrix(y_train, train_predIr))

Accuracy test: 0.9803921568627451
[[19  0]
 [ 1 31]]


Accuracy train: 1.0
[[67  0]
 [ 0 52]]


### Problem 4
In this problem, pick only the first two features and retrain the logistic regression model. Write out the accuracy and confusion matrix. (20 points)

In [105]:
y2 = y
x2 = df[df.columns[0:1]]

x_train, x_test, y_train, y_test = train_test_split(x2, y2, test_size=0.3)

lrmodel = LogisticRegression(solver='lbfgs')
lrmodel.fit(x_train, y_train)

test_ypredIr = lrmodel.predict(x_test)
train_predIr = lrmodel.predict(x_train)

print("Accuracy test:",metrics.accuracy_score(y_test, test_ypredIr))
print(confusion_matrix(y_test, test_ypredIr))
print("\n")
print("Accuracy train:",metrics.accuracy_score(y_train, train_predIr))
print(confusion_matrix(y_train, train_predIr))

Accuracy test: 0.9019607843137255
[[24  4]
 [ 1 22]]


Accuracy train: 0.8991596638655462
[[51  7]
 [ 5 56]]


### Problem 5
Make a plot of decision boundary given by your model in problem 4. You will have two plots. One plot is with the  training data and the decision boundary and the other one is with the testing data and the decision boundary. Label x axis as Featur 0  and y-axis as Feature 1. In the plot, points from test data will be classified with different colors and are separated by the decision boundary line.
(20 points)

In [106]:
x1train, x1test, y1train, y1test = train_test_split(x2, y2, test_size=0.2)
lrmodel = LogisticRegression(solver='lbfgs')
lrmodel.fit(x1train, y1train)
ypredlr = lrmodel.predict(x1test)
print("Accuracy:",metrics.accuracy_score(y1test, ypredlr))
print(confusion_matrix(y1test, ypredlr))

import numpy as np
import numpy.matlib
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import preprocessing
import seaborn as sns
import scipy.stats as st
import matplotlib.colors as colors

X = np.array(x1train)
Y = np.array(y1train)
X1=np.array(x1test)
Y1=np.array(y1test)
x_min, x_max = X[:, 0].min() - .5, X[:, 0].max() + .5
y_min, y_max = X[:, 1].min() - .5, X[:, 1].max() + .5
h = .02 # step size in the mesh
xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h)
Z = lrmodel.predict(np.c_[xx.ravel(), yy.ravel()])
# Put the result into a color plot
Z = Z.reshape(xx.shape)
plt.figure(1, figsize=(10, 10))
plt.pcolormesh(xx, yy, Z, cmap=plt.cm.Paired)
# Plot also the training/Testing points
plt.scatter(X[:, 0], X[:, 1], c=Y, edgecolors='r', cmap=plt.cm.Paired)
plt.scatter(X1[:, 0], X1[:, 1], c=Y1, edgecolors='b', cmap=plt.cm.Paired)
plt.xlabel('Feature 0: Pregnancies')
plt.ylabel('Feature 1:Glucose')
plt.xlim(xx.min(), xx.max())
plt.ylim(yy.min(), yy.max())
plt.xticks(())
plt.yticks(())
plt.show()

SyntaxError: invalid syntax (<ipython-input-106-43d999960d81>, line 26)